interface AlphaWrap {
    void AlphaWrap();
    void AlphaWrap(double alpha, double offset);

    void setAlpha(double alpha);
    void setOffset(double offset);

    void addPoint(double x, double y, double z);
    void clearPoints();

    boolean wrap();

    DOMString getWrappedMeshPly();
};
