interface AlphaWrap {
    void AlphaWrap();
    void AlphaWrap(float alpha, float offset);

    void setAlpha(float alpha);
    void setOffset(float offset);

    void addPoint(float x, float y, float z);
    void clearPoints();

    boolean wrap();

    DOMString getWrappedMeshPly();
};
