interface AlphaWrap {
    void AlphaWrap();
    void AlphaWrap(float alpha, float offset);
    void addPoint(float x, float y, float z);
    void setAlpha(float alpha);
    void setOffset(float offset);
    DOMString wrap();
};
